"""Typed API contracts for the AskANU service."""

from askanu_rag.models.contracts import (
    AskRequest,
    AskResponse,
    Clarification,
    ClarificationOption,
    ConversationState,
    ErrorResponse,
    HealthResponse,
    HistoryTurn,
    InsufficientEvidenceResponse,
    NeedsClarificationResponse,
    OffTopicResponse,
    OkResponse,
    PartialResponse,
    Source,
)
from askanu_rag.models.records import (
    CommonMetadata,
    CommonRecord,
    CourseMetadata,
    CourseProgramMetadata,
    CourseProgramRecord,
    IndexStatus,
    ProgramMetadata,
    RecordStatus,
    ScholarshipMetadata,
    ScholarshipRecord,
)

__all__ = [
    "AskRequest",
    "AskResponse",
    "Clarification",
    "ClarificationOption",
    "ConversationState",
    "CommonMetadata",
    "CommonRecord",
    "CourseMetadata",
    "CourseProgramMetadata",
    "CourseProgramRecord",
    "ErrorResponse",
    "HealthResponse",
    "HistoryTurn",
    "InsufficientEvidenceResponse",
    "IndexStatus",
    "NeedsClarificationResponse",
    "OffTopicResponse",
    "OkResponse",
    "PartialResponse",
    "ProgramMetadata",
    "RecordStatus",
    "ScholarshipMetadata",
    "ScholarshipRecord",
    "Source",
]
